# USAGE:
# GCP zone and GKE target cluster must be specified as substitutions
# Example invocation:
# `gcloud builds submit --config=cloudbuild.yaml --substitutions=_ZONE=us-central1-b,_CLUSTER=demo-app-staging .`

steps:
- id: 'Deploy application to cluster'
  name: 'gcr.io/k8s-skaffold/skaffold:v2.10.1'
  entrypoint: 'bash'
  args:
  - '-c'
  - >
    gcloud container clusters get-credentials --zone=$_ZONE $_CLUSTER;
    skaffold run -f=skaffold.yaml --default-repo=gcr.io/$PROJECT_ID;

# Add more power, and more time, for heavy Skaffold build
timeout: '3600s'
options:
  machineType: 'N1_HIGHCPU_8'
  
# [END cloudbuild_microservice_demo_cloudbuild]